name: Test Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [dev]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
            ${{ runner.OS }}
      - name: Install dependencies
        run: npm ci
      - name: Build packages/ui
        run: npm run build
      - name: Generate .env in project
        run: |
          # 추후 환경 변수 넣을 곳
          # echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_DEV_URL }}" >> .env
      - name: Test
        run: npm run test
